server:
  port: 8081

spring:
  application:
    name: trade-service

  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/traderos_db
    username: postgres
    password: newpassword
    driver-class-name: org.postgresql.Driver

  # JPA / Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: update # Automatically creates/updates tables in dev
    show-sql: false # Set to true if you want to see the generated SQL
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: localhost:19092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: trade-service-pnl-group

# Logging Configuration
logging:
  level:
    com.traderos: DEBUG
    org.springframework.kafka: INFO